package main

import (
	"errors"
	"testing"
	"time"

	"github.com/oernster/symdiary/internal/domain"
)

// The receipt as the window sends it: the lines that reach the page, in order,
// with the words a doctor ends up reading off paper (FR-040 to FR-045). They
// sit apart from app_test.go because the printed sheet is the one thing here
// that leaves the machine.

// The printed framing's exact words (FR-045), written out here rather than read
// from internal/product, for the reason donate_test.go states about the payment
// address: one of the two is the value, the other is the claim about it; a test
// comparing a constant with itself asserts nothing. The statement reaches a
// doctor on paper, so a silent edit to it must fail here.
const (
	wantedProvenance     = "Generated by SymDiary (https://symdiary.com)"
	wantedPrintStatement = "This record is not a diagnosis. It is one person's " +
		"own notes of what they observed and when, printed for a healthcare " +
		"professional to read."
)

func TestTheSheetSaysItIsNotADiagnosis(t *testing.T) {
	t.Parallel()
	// The one line on the sheet that a reader who has never met SymDiary depends
	// on. It is asserted whole, because a half of it says something else.
	app, _, _ := facade(t)
	record(t, app, RecordFormDTO{Symptom: "Tired"})

	lines, err := app.Receipt("2026-08-23", "2026-09-22", "")
	if err != nil {
		t.Fatalf("Receipt: %v", err)
	}
	var statements []string
	for _, line := range lines {
		if line.Kind == "statement" {
			statements = append(statements, line.Text)
		}
	}
	if len(statements) != 1 || statements[0] != wantedPrintStatement {
		t.Errorf("the sheet's statement lines are %q, want exactly %q",
			statements, wantedPrintStatement)
	}
}

func TestTheReceiptTheWindowSends(t *testing.T) {
	t.Parallel()
	app, clock, _ := facade(t)
	record(t, app, RecordFormDTO{Symptom: "Tired", Note: "Only been awake for about 10 minutes."})
	clock.now = clock.now.Add(time.Hour)

	lines, err := app.Receipt("2026-08-23", "2026-09-22", "")
	if err != nil {
		t.Fatalf("Receipt: %v", err)
	}
	want := []ReceiptLineDTO{
		{Kind: "provenance", Text: wantedProvenance},
		{Kind: "title", Text: "SYMPTOM RECORD"},
		{Kind: "range", Text: "23 August - 22 September 2026"},
		{Kind: "statement", Text: wantedPrintStatement},
		{Kind: "heading", Text: "Tired - 1 recorded event"},
		{Kind: "when", Text: "22 Sep 17:12"},
		{Kind: "note", Text: "Only been awake for about 10 minutes."},
	}
	if len(lines) != len(want) {
		t.Fatalf("receipt = %+v", lines)
	}
	for i := range want {
		if lines[i] != want[i] {
			t.Errorf("line %d = %+v, want %+v", i, lines[i], want[i])
		}
	}
	if _, err := app.Receipt("2026-01-01", "2026-01-31", ""); !errors.Is(err, domain.ErrEmptyRange) {
		t.Errorf("an empty range = %v", err)
	}
}

func TestTheSheetNamesTheLastAppointmentTheWindowSends(t *testing.T) {
	t.Parallel()
	// FR-046: the page decides whether to send the appointment; the sheet then
	// carries it under the range, worded as the owner approved it.
	app, _, _ := facade(t)
	record(t, app, RecordFormDTO{Symptom: "Tired"})

	lines, err := app.Receipt("2026-08-23", "2026-09-22", "2026-09-02")
	if err != nil {
		t.Fatalf("Receipt: %v", err)
	}
	if len(lines) < 4 || lines[3] != (ReceiptLineDTO{Kind: "appointment", Text: "Last appointment: 02 Sep 2026"}) {
		t.Errorf("receipt = %+v, want the appointment as its fourth line", lines)
	}
	_, err = app.Receipt("2026-09-10", "2026-09-22", "2026-09-02")
	if !errors.Is(err, domain.ErrAppointmentOutsideRange) {
		t.Errorf("an appointment outside the range = %v, want it refused", err)
	}
	if _, err := app.Receipt("2026-08-23", "2026-09-22", "soon"); err == nil {
		t.Error("an appointment that is not a date answered no error")
	}
}
