// Package product holds the facts about SymDiary that every layer may name: what
// it is called and who made it. They live here once so that a rename is one
// edit, never a search.
package product

// Name is the product name as a reader sees it.
const Name = "SymDiary"

// Author is the copyright holder.
const Author = "Oliver Ernster"

// RecordFileName is the file holding the user's symptom record. The store
// writes it; the setup program names it when it offers to delete it, so the
// two cannot disagree about which file that is.
const RecordFileName = "symdiary.db"

// Copyright is the notice About shows (FR-066). The year is the year of the
// first release rather than the year the program is run in: a notice that
// silently follows the clock claims a date nothing was published on.
const Copyright = "© " + Author + " 2026"

// DonateURL is where the donate button sends a browser (FR-069). It is the
// only address SymDiary knows; it is handed to the desktop rather than fetched,
// so nothing here ever opens a connection of its own.
const DonateURL = "https://www.paypal.com/ncp/payment/4XP3AYNMPQGUC"

// HomeURL is where SymDiary lives. Like DonateURL it is only ever printed or
// handed to the desktop; nothing here opens a connection of its own.
const HomeURL = "https://symdiary.com"

// PrintProvenance names the program that produced a printed record, once, above
// its title (FR-045). A sheet outlives the window it came from, so it says what
// made it.
const PrintProvenance = "Generated by " + Name + " (" + HomeURL + ")"

// PrintStatement is what the printed record says about itself (FR-045). It is
// not Statement: that one speaks to the person using SymDiary, while this one
// speaks to the professional reading a sheet, about the sheet in their hand.
//
// It says notes rather than guidance deliberately. MHRA guidance v1.10f treats
// software providing information towards a clinical decision as its own
// category; a sheet claiming to be an input to that decision would describe a
// purpose SymDiary does not have (REQUIREMENTS.md 4.1).
const PrintStatement = "This record is not a diagnosis. It is one person's " +
	"own notes of what they observed and when, printed for a healthcare " +
	"professional to read."

// Statement is what SymDiary is and is not, shown in About (FR-067).
const Statement = "SymDiary records what you observed and when. " +
	"It gives no medical advice and does not interpret your symptoms; " +
	"that is for you and your healthcare professional."
