package domain

import (
	"errors"
	"slices"
	"testing"
	"time"
)

// sample answers the FR-041 acceptance events: Headache on 25 Aug and 2 Sep,
// Tired on 28 Aug and 22 Sep, handed over out of order.
func sample(t *testing.T) []Event {
	t.Helper()
	tired := event(4, 1, "Tired", at(t, 2026, time.September, 22, 17, 12))
	tired.Note = "Only been awake for about 10 minutes."
	headache := event(2, 2, "Headache", at(t, 2026, time.September, 2, 8, 10))
	headache.Severity = SeverityModerate
	return []Event{
		tired,
		event(3, 1, "Tired", at(t, 2026, time.August, 28, 7, 45)),
		headache,
		event(1, 2, "Headache", at(t, 2026, time.August, 25, 12, 30)),
		event(5, 2, "Headache", at(t, 2026, time.August, 22, 23, 59)),
	}
}

// testFraming stands in for the product's own words, which live in
// internal/product and which the domain may not import. Both lines are written
// so that nothing else in a receipt could be mistaken for them.
var testFraming = Framing{
	Provenance: "Generated by Example (https://example.invalid)",
	Statement:  "This record is not a diagnosis.",
}

// lineTexts answers the text of each line.
func lineTexts(lines []Line) []string {
	out := make([]string, 0, len(lines))
	for _, line := range lines {
		out = append(out, line.Text)
	}
	return out
}

// assertLines fails unless got holds exactly the wanted texts.
func assertLines(t *testing.T, got []Line, want []string) {
	t.Helper()
	texts := lineTexts(got)
	if len(texts) != len(want) {
		t.Fatalf("receipt =\n%q\nwant\n%q", texts, want)
	}
	for i := range want {
		if texts[i] != want[i] {
			t.Fatalf("line %d = %q, want %q\nwhole receipt: %q", i, texts[i], want[i], texts)
		}
	}
}

func TestReceiptMatchesTheAcceptanceExample(t *testing.T) {
	t.Parallel()
	receipt, err := BuildReceipt(sample(t),
		Date{2026, time.August, 23}, Date{2026, time.September, 22}, london(t))
	if err != nil {
		t.Fatalf("BuildReceipt: %v", err)
	}
	assertLines(t, receipt.Lines(testFraming), []string{
		testFraming.Provenance,
		"SYMPTOM RECORD",
		"23 August - 22 September 2026",
		testFraming.Statement,
		"Headache - 2 recorded events",
		"25 Aug 12:30",
		"02 Sep 08:10",
		"Severity: Moderate",
		"Tired - 2 recorded events",
		"28 Aug 07:45",
		"22 Sep 17:12",
		"Only been awake for about 10 minutes.",
	})
}

func TestReceiptOrder(t *testing.T) {
	t.Parallel()
	// Zebra first occurs before Aardvark, so it comes first whatever the alphabet
	// says; Aardvark has more events and that does not move it up either.
	events := []Event{
		event(1, 1, "Aardvark", at(t, 2026, time.September, 5, 9, 0)),
		event(2, 1, "Aardvark", at(t, 2026, time.September, 6, 9, 0)),
		event(3, 1, "Aardvark", at(t, 2026, time.September, 7, 9, 0)),
		event(4, 2, "Zebra", at(t, 2026, time.September, 4, 9, 0)),
	}
	receipt, err := BuildReceipt(events,
		Date{2026, time.September, 1}, Date{2026, time.September, 30}, london(t))
	if err != nil {
		t.Fatalf("BuildReceipt: %v", err)
	}
	if receipt.Groups[0].Symptom != "Zebra" || receipt.Groups[1].Symptom != "Aardvark" {
		t.Errorf("group order = %s, %s; want Zebra, Aardvark",
			receipt.Groups[0].Symptom, receipt.Groups[1].Symptom)
	}
	aardvark := receipt.Groups[1].Events
	if aardvark[0].ID != 1 || aardvark[2].ID != 3 {
		t.Errorf("events within a group should run oldest first: %+v", aardvark)
	}
}

func TestReceiptHoldsNoOtherText(t *testing.T) {
	t.Parallel()
	receipt, err := BuildReceipt(sample(t),
		Date{2026, time.August, 23}, Date{2026, time.September, 22}, london(t))
	if err != nil {
		t.Fatalf("BuildReceipt: %v", err)
	}
	// Named, so the one line that varies with something other than an event is
	// held to exactly what the user marked.
	receipt, err = receipt.WithAppointment(Date{2026, time.September, 2})
	if err != nil {
		t.Fatalf("WithAppointment: %v", err)
	}
	allowed := map[LineKind]bool{
		LineTitle: true, LineRange: true, LineHeading: true,
		LineWhen: true, LineSeverity: true, LineNote: true,
		LineProvenance: true, LineStatement: true, LineAppointment: true,
	}
	notes := map[string]bool{"Only been awake for about 10 minutes.": true}
	for _, line := range receipt.Lines(testFraming) {
		if !allowed[line.Kind] {
			t.Errorf("line %q has kind %q, which a receipt does not hold", line.Text, line.Kind)
		}
		if line.Kind == LineNote && !notes[line.Text] {
			t.Errorf("note line %q is not a note the user wrote", line.Text)
		}
		if line.Kind == LineProvenance && line.Text != testFraming.Provenance {
			t.Errorf("provenance line %q is not the framing it was handed", line.Text)
		}
		if line.Kind == LineStatement && line.Text != testFraming.Statement {
			t.Errorf("statement line %q is not the framing it was handed", line.Text)
		}
		if line.Kind == LineAppointment && line.Text != "Last appointment: 02 Sep 2026" {
			t.Errorf("appointment line %q is not the date the user marked", line.Text)
		}
	}
}

func TestTheLastAppointmentSitsUnderTheRange(t *testing.T) {
	t.Parallel()
	// The acceptance example of FR-046: the line follows the range and comes
	// before the statement, which it pushes down by one and otherwise leaves be.
	receipt, err := BuildReceipt(sample(t),
		Date{2026, time.August, 23}, Date{2026, time.September, 22}, london(t))
	if err != nil {
		t.Fatalf("BuildReceipt: %v", err)
	}
	receipt, err = receipt.WithAppointment(Date{2026, time.September, 2})
	if err != nil {
		t.Fatalf("WithAppointment: %v", err)
	}
	lines := receipt.Lines(testFraming)
	assertLines(t, lines[:5], []string{
		testFraming.Provenance,
		"SYMPTOM RECORD",
		"23 August - 22 September 2026",
		"Last appointment: 02 Sep 2026",
		testFraming.Statement,
	})
	if lines[3].Kind != LineAppointment {
		t.Errorf("the appointment line has kind %q, want %q", lines[3].Kind, LineAppointment)
	}
}

func TestTheLastAppointmentIsNamedOnlyWithinTheRange(t *testing.T) {
	t.Parallel()
	appointment := Date{2026, time.September, 2}
	cases := []struct {
		name     string
		from, to Date
		named    bool
	}{
		{"the range starts on it", appointment, Date{2026, time.September, 22}, true},
		{"the range starts on it and ends earlier", appointment, Date{2026, time.September, 15}, true},
		{"the range spans it", Date{2026, time.August, 1}, Date{2026, time.September, 22}, true},
		{"the range ends on it", Date{2026, time.August, 23}, appointment, true},
		{"the range starts after it", Date{2026, time.September, 10}, Date{2026, time.September, 22}, false},
		{"the range ends before it", Date{2026, time.August, 1}, Date{2026, time.August, 31}, false},
	}
	for _, c := range cases {
		receipt, err := BuildReceipt(sample(t), c.from, c.to, london(t))
		if err != nil {
			t.Fatalf("%s: BuildReceipt: %v", c.name, err)
		}
		named, err := receipt.WithAppointment(appointment)
		if c.named && err != nil {
			t.Errorf("%s: WithAppointment = %v, want it named", c.name, err)
		}
		if !c.named && !errors.Is(err, ErrAppointmentOutsideRange) {
			t.Errorf("%s: WithAppointment = %v, want ErrAppointmentOutsideRange", c.name, err)
		}
		if !c.named && !named.Appointment.IsZero() {
			t.Errorf("%s: a refused appointment was kept", c.name)
		}
	}
}

func TestNoAppointmentAddsNoLine(t *testing.T) {
	t.Parallel()
	receipt, err := BuildReceipt(sample(t),
		Date{2026, time.August, 23}, Date{2026, time.September, 22}, london(t))
	if err != nil {
		t.Fatalf("BuildReceipt: %v", err)
	}
	unnamed, err := receipt.WithAppointment(Date{})
	if err != nil {
		t.Fatalf("WithAppointment with none: %v", err)
	}
	if !slices.Equal(lineTexts(unnamed.Lines(testFraming)), lineTexts(receipt.Lines(testFraming))) {
		t.Error("a receipt naming no appointment differs from one never asked to")
	}
}

func TestTheFramingOpensTheRecord(t *testing.T) {
	t.Parallel()
	receipt, err := BuildReceipt(sample(t),
		Date{2026, time.August, 23}, Date{2026, time.September, 22}, london(t))
	if err != nil {
		t.Fatalf("BuildReceipt: %v", err)
	}
	lines := receipt.Lines(testFraming)
	first := lines[0]
	if first.Kind != LineProvenance || first.Text != testFraming.Provenance {
		t.Errorf("the sheet opens with %+v, want the provenance", first)
	}
	for _, line := range lines[1:] {
		if line.Kind == LineProvenance {
			t.Error("the provenance is printed more than once")
		}
	}
	// The statement sits under the range, so it is read before any event.
	if lines[3].Kind != LineStatement || lines[3].Text != testFraming.Statement {
		t.Errorf("line 4 is %+v, want the statement under the range", lines[3])
	}
	for _, line := range lines[4:] {
		if line.Kind == LineStatement {
			t.Error("the statement is printed more than once")
		}
	}
}

func TestTheFramingIsTheSameWhateverTheRecord(t *testing.T) {
	t.Parallel()
	// The framing states nothing about what was recorded (FR-042), so two
	// receipts holding different events must carry identical framing lines.
	zone := london(t)
	full, err := BuildReceipt(sample(t),
		Date{2026, time.August, 23}, Date{2026, time.September, 22}, zone)
	if err != nil {
		t.Fatalf("BuildReceipt: %v", err)
	}
	day := Date{2026, time.September, 22}
	one, err := BuildReceipt(sample(t)[:1], day, day, zone)
	if err != nil {
		t.Fatalf("BuildReceipt: %v", err)
	}
	if got, want := framingOf(full.Lines(testFraming)), framingOf(one.Lines(testFraming)); !slices.Equal(got, want) {
		t.Errorf("framing = %q on one record and %q on another", got, want)
	}
}

// framingOf answers the text of the framing lines, in the order they print.
func framingOf(lines []Line) []string {
	var out []string
	for _, line := range lines {
		if line.Kind == LineProvenance || line.Kind == LineStatement {
			out = append(out, line.Text)
		}
	}
	return out
}

func TestReceiptAcrossAYearNamesTheYear(t *testing.T) {
	t.Parallel()
	events := []Event{
		event(1, 1, "Tired", at(t, 2025, time.December, 30, 9, 0)),
		event(2, 1, "Tired", at(t, 2026, time.January, 2, 9, 0)),
	}
	receipt, err := BuildReceipt(events,
		Date{2025, time.December, 23}, Date{2026, time.January, 22}, london(t))
	if err != nil {
		t.Fatalf("BuildReceipt: %v", err)
	}
	assertLines(t, receipt.Lines(testFraming), []string{
		testFraming.Provenance,
		"SYMPTOM RECORD",
		"23 December 2025 - 22 January 2026",
		testFraming.Statement,
		"Tired - 2 recorded events",
		"30 Dec 2025 09:00",
		"02 Jan 2026 09:00",
	})
}

func TestReceiptOfOneDayAndOneEvent(t *testing.T) {
	t.Parallel()
	day := Date{2026, time.September, 22}
	receipt, err := BuildReceipt(sample(t)[:1], day, day, london(t))
	if err != nil {
		t.Fatalf("BuildReceipt: %v", err)
	}
	lines := lineTexts(receipt.Lines(testFraming))
	if lines[2] != "22 September 2026" || lines[4] != "Tired - 1 recorded event" {
		t.Errorf("one day, one event reads %q", lines)
	}
}

func TestEmptyRangeGivesNoReceipt(t *testing.T) {
	t.Parallel()
	zone := london(t)
	_, err := BuildReceipt(sample(t), Date{2026, time.July, 1}, Date{2026, time.July, 31}, zone)
	if !errors.Is(err, ErrEmptyRange) {
		t.Errorf("July = %v, want ErrEmptyRange", err)
	}
	_, err = BuildReceipt(sample(t), Date{}, Date{2026, time.July, 31}, zone)
	if !errors.Is(err, ErrOpenRange) {
		t.Errorf("no start = %v, want ErrOpenRange", err)
	}
	_, err = BuildReceipt(sample(t), Date{2026, time.July, 31}, Date{2026, time.July, 1}, zone)
	if !errors.Is(err, ErrReversedRange) {
		t.Errorf("reversed = %v, want ErrReversedRange", err)
	}
}
